version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/ui/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Composer
  - package-ecosystem: "cargo"
    directory: "/src-tauri/"
    schedule:
      interval: "daily"
