[package]
name = "orange_git_fish"
version = "0.1.0"
build = "src/build.rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.2.4"
git2 = "0.14"

[build-dependencies]
slint-build = "0.2.4"
